name: Run tests

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: true
        cache-environment-key: requirements-${{ hashFiles('requirements*.txt') }}

    - name: Run pytest
      run: |
        mamba activate fica
        make testcov
        coverage xml

    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
