name: Run tests

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

jobs:
  build:
    name: Test suite
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
        cache-environment: true
        cache-environment-key: requirements-${{ hashFiles('requirements*.txt') }}

    - name: Run pytest
      run: |
        micromamba activate fica
        make testcov
        coverage lcov -i

    - name: Coveralls
      uses: coverallsapp/github-action@v2
