name: Run tests

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

jobs:
  build:
    name: Test suite
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2

      - uses: liskin/gh-pipx@v1
        with:
          packages: >-
            poetry

      - name: Install dependencies
        run: |
          poetry env use 3
          poetry install --no-root --with test

      - name: Run pytest
        run: |
          poetry env use 3
          make testcov
          coverage lcov -i

      - name: Coveralls
        uses: coverallsapp/github-action@v2
